"""Initial migration

Revision ID: 33fedaba723d
Revises: 
Create Date: 2024-08-03 00:12:25.369300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33fedaba723d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_index('ix_users_usuario', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'usuario')
    op.drop_column('users', 'contraseña')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contraseña', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('usuario', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_usuario', 'users', ['usuario'], unique=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
